### ISSUE TITLE
failure while updating a file using absolute path

### ISSUE THREAD

**Issue by dhaubert** [williamwd/useful-scripts#1]
That was I got on cli terminal 
`[11:52]douglas@selenium:LC_MESSAGES$ svn up /var/www/api/v1/
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
svn: E125001: Couldn't determine absolute path of '.'
svn: E000002: No such file or directory
/bin/pwd: couldn't find directory entry in ‘..’ with matching i-node
/bin/pwd: couldn't find directory entry in ‘..’ with matching i-node`

I think I was inside the '/var/www/br-html/locales_general/locales/pt_PT/LC_MESSAGES/' directory.

The bot showed up the command and the username, but it failed trying to get the 'Current path' and the 'Output'.

BR, Douglas.

**Comment by williamwd** [comment]
Can you reproduce the bug?

**Comment by dhaubert** [comment]
Nope, I am closing the issue.
